### ISSUE TITLE
Crash on Crafting Iron Pickaxe

### ISSUE THREAD

**Issue by BlazinFyre** [MinestrapTeam/Minestrappolation-2#387]
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 12/1/14 1:42 AM
Description: Updating screen events

java.lang.ArrayIndexOutOfBoundsException: -1
    at net.minecraft.item.ItemStack.func_77980_a(ItemStack.java:386)
    at net.minecraft.inventory.SlotCrafting.func_75208_c(SlotCrafting.java:53)
    at net.minecraft.inventory.SlotCrafting.func_75210_a(SlotCrafting.java:48)
    at net.minecraft.inventory.Slot.func_75220_a(Slot.java:45)
    at net.minecraft.inventory.ContainerWorkbench.func_82846_b(SourceFile:88)
    at net.minecraft.inventory.Container.func_75144_a(SourceFile:193)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:641)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:607)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1629)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.item.ItemStack.func_77980_a(ItemStack.java:386)
    at net.minecraft.inventory.SlotCrafting.func_75208_c(SlotCrafting.java:53)
    at net.minecraft.inventory.SlotCrafting.func_75210_a(SlotCrafting.java:48)
    at net.minecraft.inventory.Slot.func_75220_a(Slot.java:45)
    at net.minecraft.inventory.ContainerWorkbench.func_82846_b(SourceFile:88)
    at net.minecraft.inventory.Container.func_75144_a(SourceFile:193)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:641)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:607)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
    Screen name: net.minecraft.client.gui.inventory.GuiCrafting

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Telamon1'/287, l='MpServer', x=-105.03, y=50.62, z=-75.07]]
    Chunk stats: MultiplayerChunkCache: 167, 169
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (80,64,40), Chunk: (at 0,4,8 in 5,2; contains blocks 80,0,32 to 95,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 30512 game time, 30512 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 53 total; [EntityBat['Bat'/0, l='MpServer', x=-96.25, y=14.10, z=-107.50], EntityBat['Bat'/1, l='MpServer', x=-96.44, y=14.10, z=-107.56], EntityBat['Bat'/2, l='MpServer', x=-96.25, y=15.10, z=-110.69], EntityBat['Bat'/4, l='MpServer', x=-108.75, y=33.10, z=-87.25], EntitySheep['Sheep'/5, l='MpServer', x=-105.72, y=66.00, z=-43.47], EntityHorse['Horse'/6, l='MpServer', x=-111.03, y=69.00, z=-45.00], EntityHorse['Horse'/7, l='MpServer', x=-109.50, y=69.00, z=-43.13], EntitySheep['Sheep'/8, l='MpServer', x=-103.63, y=70.00, z=-32.47], EntitySheep['Sheep'/9, l='MpServer', x=-101.50, y=71.00, z=-28.50], EntityItem['item.item.rottenFlesh'/27, l='MpServer', x=-91.22, y=72.13, z=-115.81], EntityBat['Bat'/29, l='MpServer', x=-85.53, y=52.10, z=-58.25], EntityItem['item.item.rottenFlesh'/28, l='MpServer', x=-88.56, y=73.13, z=-104.94], EntityBat['Bat'/30, l='MpServer', x=-87.44, y=52.10, z=-63.75], EntityItem['item.item.arrow'/34, l='MpServer', x=-70.13, y=63.13, z=-23.13], EntityBat['Bat'/442, l='MpServer', x=-120.31, y=25.00, z=-108.34], EntityBat['Bat'/443, l='MpServer', x=-111.84, y=16.32, z=-118.56], EntityPig['Pig'/42, l='MpServer', x=-49.50, y=71.00, z=-146.50], EntityPig['Pig'/43, l='MpServer', x=-48.53, y=69.00, z=-145.53], EntityBat['Bat'/40, l='MpServer', x=-73.56, y=32.93, z=-144.75], EntityHorse['Horse'/46, l='MpServer', x=-48.97, y=72.00, z=-121.97], EntityHorse['Horse'/47, l='MpServer', x=-50.91, y=71.00, z=-125.62], EntityHorse['Horse'/44, l='MpServer', x=-49.94, y=71.00, z=-128.06], EntityHorse['Horse'/45, l='MpServer', x=-49.50, y=71.00, z=-123.50], EntityClientPlayerMP['Telamon1'/287, l='MpServer', x=-105.03, y=50.62, z=-75.07], EntitySheep['Sheep'/51, l='MpServer', x=-50.13, y=70.00, z=-47.88], EntityBat['Bat'/289, l='MpServer', x=-108.71, y=19.02, z=-92.34], EntitySheep['Sheep'/50, l='MpServer', x=-54.19, y=82.00, z=-60.88], EntityChicken['Chicken'/290, l='MpServer', x=-119.53, y=68.00, z=-77.53], EntitySheep['Sheep'/49, l='MpServer', x=-56.78, y=70.00, z=-49.13], EntitySheep['Sheep'/48, l='MpServer', x=-61.06, y=72.00, z=-67.06], EntityChicken['Chicken'/291, l='MpServer', x=-127.44, y=69.00, z=-88.44], EntityChicken['Chicken'/292, l='MpServer', x=-143.63, y=66.00, z=-60.63], EntitySheep['Sheep'/293, l='MpServer', x=-112.19, y=72.00, z=-27.91], EntitySheep['Sheep'/53, l='MpServer', x=-53.50, y=72.00, z=-73.47], EntityItem['item.item.seeds'/294, l='MpServer', x=-156.72, y=61.13, z=-42.41], EntityItem['item.item.seeds'/295, l='MpServer', x=-145.50, y=65.13, z=-106.13], EntitySheep['Sheep'/52, l='MpServer', x=-68.09, y=71.00, z=-40.06], EntityItem['item.item.seeds'/296, l='MpServer', x=-152.97, y=67.13, z=-128.00], EntityItem['item.item.seeds'/297, l='MpServer', x=-149.81, y=63.13, z=-129.91], EntityHorse['Horse'/63, l='MpServer', x=-46.56, y=71.00, z=-133.78], EntityHorse['Horse'/62, l='MpServer', x=-45.19, y=71.00, z=-129.44], EntityPig['Pig'/61, l='MpServer', x=-46.47, y=68.00, z=-144.50], EntityPig['Pig'/60, l='MpServer', x=-48.50, y=67.00, z=-143.53], EntitySheep['Sheep'/68, l='MpServer', x=-39.19, y=72.00, z=-40.50], EntitySheep['Sheep'/69, l='MpServer', x=-42.50, y=80.00, z=-42.50], EntitySheep['Sheep'/64, l='MpServer', x=-32.19, y=72.00, z=-94.28], EntitySheep['Sheep'/65, l='MpServer', x=-35.50, y=79.00, z=-94.50], EntitySheep['Sheep'/66, l='MpServer', x=-33.28, y=72.00, z=-95.56], EntitySheep['Sheep'/67, l='MpServer', x=-43.66, y=71.00, z=-35.22], EntitySheep['Sheep'/76, l='MpServer', x=-27.50, y=69.00, z=-72.50], EntitySheep['Sheep'/77, l='MpServer', x=-27.47, y=75.00, z=-74.53], EntitySheep['Sheep'/78, l='MpServer', x=-27.47, y=75.00, z=-73.47], EntitySheep['Sheep'/79, l='MpServer', x=-28.53, y=74.00, z=-74.53]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 199636696 bytes (190 MB) / 405082112 bytes (386 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.05 FML v7.10.85.1240 Minecraft Forge 10.13.2.1240 8 mods loaded, 8 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1240} [Forge Mod Loader](forge-1.7.10-10.13.2.1240.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1240} [Minecraft Forge](forge-1.7.10-10.13.2.1240.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    cslib{1.7.10-2.7.2} [Clashsoft Lib](ClashsoftLib-1.7.10-2.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    brewingapi{1.7.10-3.0.2} [Brewing API](BrewingAPI-1.7.10-3.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CavesAPI{1.0} [Caves API](ElementalCaves-1.7.2-1.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ElementalCaves{1.7.2-1.1.3} [Elemental Caves](ElementalCaves-1.7.2-1.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    minestrappolation{1.7.10-3.3.4} [Minestrappolation](Minestrappolation-1.7.10-3.3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Launched Version: 1.7.10-Forge10.13.2.1240
    LWJGL: 2.9.1
    OpenGL: AMD Radeon HD 6670 GL version 4.2.11631 Compatibility Profile Context, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by Lird06** [comment]
me too,i can't craft wooden sword - -,how to fix it?

**Comment by medsal15** [comment]
Download minestrappoilation 4 when it's out.

**Comment by Lird06** [comment]
oh,can you tell me how to download it?

**Comment by werty1124** [comment]
@Lird06 It has been fixed in M4!
