### ISSUE TITLE
Crafting Crash

### ISSUE THREAD

**Issue by Kush-Prajapati** [MinestrapTeam/Minestrappolation-2#388]
```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 12/2/14 7:44 PM
Description: Updating screen events

java.lang.ArrayIndexOutOfBoundsException: -1
    at net.minecraft.item.ItemStack.func_77980_a(ItemStack.java:386)
    at net.minecraft.inventory.SlotCrafting.func_75208_c(SlotCrafting.java:53)
    at net.minecraft.inventory.SlotCrafting.func_82870_a(SlotCrafting.java:110)
    at net.minecraft.inventory.Container.func_75144_a(SourceFile:238)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
    at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:534)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
    at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
    at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
    at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
    at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:464)
    at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:394)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1629)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
    at org.multimc.EntryPoint.listen(EntryPoint.java:165)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.minecraft.item.ItemStack.func_77980_a(ItemStack.java:386)
    at net.minecraft.inventory.SlotCrafting.func_75208_c(SlotCrafting.java:53)
    at net.minecraft.inventory.SlotCrafting.func_82870_a(SlotCrafting.java:110)
    at net.minecraft.inventory.Container.func_75144_a(SourceFile:238)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
    at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:534)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
    at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
    at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
    at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
    at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:464)
    at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:394)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
    Screen name: net.minecraft.client.gui.inventory.GuiCrafting

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['riroc815'/768, l='MpServer', x=670.66, y=49.62, z=246.70]]
    Chunk stats: MultiplayerChunkCache: 121, 121
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (643,64,292), Chunk: (at 3,4,4 in 40,18; contains blocks 640,0,288 to 655,255,303), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
    Level time: 4887 game time, 4887 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 27 total; [EntityClientPlayerMP['riroc815'/768, l='MpServer', x=670.66, y=49.62, z=246.70], EntityZombie['Zombie'/1822, l='MpServer', x=46.65, y=-27.54, z=19.55], EntityBat['Bat'/3930, l='MpServer', x=672.19, y=17.75, z=271.68], EntityPig['Pig'/605, l='MpServer', x=638.41, y=71.00, z=182.69], EntityPig['Pig'/618, l='MpServer', x=653.06, y=70.00, z=172.06], EntityPig['Pig'/624, l='MpServer', x=640.53, y=73.00, z=181.84], EntityPig['Pig'/625, l='MpServer', x=640.47, y=76.00, z=177.31], EntityBat['Bat'/2422, l='MpServer', x=662.47, y=58.22, z=241.52], EntityPig['Pig'/662, l='MpServer', x=679.50, y=67.69, z=265.60], EntityPig['Pig'/664, l='MpServer', x=689.31, y=64.00, z=294.44], EntityPig['Pig'/675, l='MpServer', x=689.47, y=63.00, z=295.38], EntityItem['item.tile.sapling.oak'/2731, l='MpServer', x=691.25, y=75.13, z=227.75], EntityBat['Bat'/2989, l='MpServer', x=731.21, y=38.00, z=249.34], EntityItem['item.item.seeds'/1206, l='MpServer', x=688.22, y=70.13, z=244.41], EntityPig['Pig'/724, l='MpServer', x=732.22, y=75.00, z=207.50], EntityPig['Pig'/725, l='MpServer', x=740.50, y=71.00, z=204.50], EntityPig['Pig'/726, l='MpServer', x=746.47, y=70.00, z=206.34], EntityPig['Pig'/727, l='MpServer', x=738.88, y=71.00, z=216.16], EntityPig['Pig'/728, l='MpServer', x=742.50, y=70.00, z=282.50], EntityPig['Pig'/729, l='MpServer', x=743.50, y=70.00, z=280.50], EntityPig['Pig'/730, l='MpServer', x=742.50, y=71.00, z=280.50], EntityPig['Pig'/731, l='MpServer', x=739.50, y=71.00, z=281.50], EntityBat['Bat'/3297, l='MpServer', x=652.25, y=15.10, z=266.75], EntityItem['item.tile.flower2.poppy'/1519, l='MpServer', x=625.78, y=67.13, z=293.97], EntityItem['item.tile.sapling.oak'/3312, l='MpServer', x=688.19, y=76.13, z=232.28], EntityItem['item.item.apple'/3313, l='MpServer', x=688.13, y=71.13, z=231.13], EntityItem['item.tile.sapling.oak'/3316, l='MpServer', x=684.78, y=70.13, z=232.84]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
    at org.multimc.EntryPoint.listen(EntryPoint.java:165)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 76955800 bytes (73 MB) / 519110656 bytes (495 MB) up to 1037959168 bytes (989 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.05 FML v7.10.85.1240 Minecraft Forge 10.13.2.1240 11 mods loaded, 11 mods active
    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    FML{7.10.85.1240} [Forge Mod Loader] (forge-1.7.10-10.13.2.1240-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Forge{10.13.2.1240} [Minecraft Forge] (forge-1.7.10-10.13.2.1240-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    CodeChickenCore{1.0.2.9} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    NotEnoughItems{1.0.2.15} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.2.15-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    cslib{1.7.10-2.7.2} [Clashsoft Lib] (ClashsoftLib-1.7.10-2.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    brewingapi{1.7.10-3.0.2} [Brewing API] (BrewingAPI-1.7.10-3.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    cshud{1.7.10-2.1.2} [Clashsoft's HUD Mod] (ClashsoftHUD-1.7.10-2.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    FastCraft{1.9} [FastCraft] (fastcraft-1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    minestrappolation{1.7.10-3.3.4} [Minestrappolation] (Minestrappolation-1.7.10-3.3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Launched Version: 1.7.10
    LWJGL: 2.9.1
    OpenGL: GeForce 6150 LE/integrated/SSE2 GL version 2.1.2, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Anisotropic Filtering: Off (1)
```

**Comment by AlexGamer1646** [comment]
Where I can find that readne file?

**Comment by LandKingdom** [comment]
In the next release!
